// Importing mongoose library for MongoDB interactions
import mongoose from "mongoose";

// Defining the project schema using mongoose
const projectSchema = new mongoose.Schema({
    // Name of the project
    name: String,
    // Description of the project
    description: String,
    // Author or creator of the project
    author: String,
    // Timestamp for when the project was posted, with a default value generated by the formatDate function
    postTime: {
        type: String,
        default: () => formatDate()
    }
});

// Creating a model based on the defined schema
const ProjectModel = mongoose.model('projects', projectSchema);

// Exporting the ProjectModel
export default ProjectModel;

// Function to format the current date and time
function formatDate() {
    // Array of month abbreviations
    const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  
    // Creating a new Date object for the current date and time
    const currentDate = new Date();
  
    // Extracting hours, minutes, day, month, and year from the current date
    const hours = String(currentDate.getHours()).padStart(2, '0');
    const minutes = String(currentDate.getMinutes()).padStart(2, '0');
    const day = String(currentDate.getDate()).padStart(2, '0');
    const month = months[currentDate.getMonth()];
    const year = currentDate.getFullYear();
  
    // Constructing a formatted date and time string
    const formattedDateTime = `${hours}:${minutes} ${day}${month} ${year}`;
  
    // Returning the formatted date and time string
    return formattedDateTime;
}
